sample_project/sample_app/urls.py
from sample_app import views
from django.urls import path

#TEMPLATE TAGGING - allowing the use of e.g. relative url in templates
app_name = 'sample_app'

urlpatterns = [
    #Example in HTML: <a href="{% url 'sample_app:relative' %}
    # 'sample_app' refers to the app_name
    # 'relative refers' to the name attribute below
    #This allows dev to avoid including actual paths in HTML.
    path('relative/', views.relative_url_templates, name='relative'),
    path('help/', views.help, name="help"),
    path('users/', views.user, name="users"),
    path('formpage/', views.form_name_view, name='form_name'),
    path('userformpage/', views.form_user_enter, name='form_enter_user'),
    # path('base_temp/', views.base_template, name='base_template')
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('features_test/', views.features_test, name='features_test'),
]

sample_project/sample_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from sample_app import views

from django.conf import settings
from django.conf.urls.static import static

from sqlapp.sqlapp import execute_sql

urlpatterns = [
    path('', views.index, name="index"),
    re_path('^admin/sqlapp/(?:sql/)?$', execute_sql, name='sql'),
    path('admin/', admin.site.urls),
    path('sample_app/', include('sample_app.urls')), #including all the urls in sample_app/urls.py
    path('logout/', views.user_logout, name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#The last bit above is to place the media folders on the url so
#their content can be served in the browser (e.g. in the Admin page) -
#this is not taught in the Udemy course but comes from here:
#https://docs.djangoproject.com/es/3.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development

sample_project/sample_app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING) #Newer version of Django requires on_delete in this constructor
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.DO_NOTHING)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

#sample_app's User (not admin's User)
class WebUser(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=264, unique=True)
    DoB = models.DateField(default=datetime.now, blank=False)
    notes = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

class UserProfileInfo(models.Model):
    #Exending the User class WITHOUT inheriting User class
    #because this is NOT another User instance.
    #In OOP design this is one-to-one composition
    #https://docs.djangoproject.com/en/4.0/topics/db/examples/one_to_one/
    #and instances of the two classes can actually refer to each other
    #E.g.:
    #up = UserProfileInf(user = some_user)
    #some_user.userprofileinfo is now referencing up as well.
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    # additional members outside of User
    portfolio_site = models.URLField(blank=True)
    # note that profile_pics is a folder under media
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

sample_project/sample_app/forms.py
from django import forms
from django.core import validators
from sample_app.models import WebUser, UserProfileInfo
from django.contrib.auth.models import User

#A way to implement custom validator
#Django expects the parameter "value"
#Use this later, e.g.: #name = forms.CharField(validators=[check_for_z])
def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name need to start with 'z'")

class FormName(forms.Form):
    #name = forms.CharField(validators=[check_for_z])
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again:")
    text = forms.CharField(widget=forms.Textarea)
    #a bot would blindly add a value to this hidden input field
    #which helps identify that it is a bot
    botcatcher = forms.CharField(required=False,
                                widget=forms.HiddenInput,
                                validators=[validators.MaxLengthValidator(0)])

    #clean method - all such methods start with "clean_" and the name
    #of the field to be cleaned - Django's convention
    #This method will be run by Django to show an error message on the
    #form when validation fails.
    #Note: It is better to use built-in validators from django.core.
    #But this is better for more special cases.
    '''
    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']

        if len(botcatcher) > 0:
            raise forms.ValidationError("GOTCHA BOT!")

        return botcatcher
    '''

    #Django convention: clean everything!
    def _clean(self):
        all_clean_data = super().clean() #return all clean data
        email = all_clean_data["email"]
        vmail = all_clean_data["verify_email"]

        if email != vmail:
            raise forms.ValidationError("Emails not matched.")

class FormWebUser(forms.ModelForm):
    #Can include the fields here or NOT (as they will be automatically
    #generated if fields = "__all__")
    class Meta:
        model = WebUser
        #ALSO OK: a tuple of some fields or exclude = [list of excluded field]
        fields = "__all__"


class FormUser(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class FormUserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        exclude = ('user',) #everything except for the on-to-one user field

sample_project/sample_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from sample_app.models import Topic, AccessRecord, Webpage, WebUser
from . import forms
from django.urls import reverse #new from Django 2
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

#Just by calling a method here can trigger the navigation to that page
#However, the url in the browser isn't changed. Perhaps fix that with JavaScript?
def index(request):
    user_name = None
    try:
        if (request.user):
            user_name = request.user.username
            print(f"Username: {user_name}")
    except:
        print("User not logged in.")

    return render(request, 'sample_app/index.html', context={'user_name': user_name})

def features_test(request):

    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records' : webpages_list}

    return render(request, 'sample_app/features_test.html', context=date_dict)

def help(request):
    my_dict = {'help_info' : 'This is some help info.'}
    return render(request, 'sample_app/help.html', context = my_dict)

@login_required
def user(request):
    user_list = WebUser.objects.order_by('last_name')
    user_dict = {'user_records' : user_list}

    return render(request, 'sample_app/users.html', context=user_dict)

@login_required
def relative_url_templates(request):
    return render(request, 'sample_app/relative_url_templates.html')

# def base_template(request):
#     return render(request, 'sample_app/base.html')

@login_required
def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS")
            print("NAME: " + form.cleaned_data['name'])
            print("EMAIL: " + form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])
        else:
            print("FORM VALIDATION FAILED")

    return render(request, "sample_app/form_page.html", {'form': form})

@login_required
def form_user_enter(request):
    form = forms.FormWebUser()

    if request.method == 'POST':
        form = forms.FormWebUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request) #go back to the home page
        else:
            print("FORM VALIDATION FAILED")

    return render(request, "sample_app/userform_page.html", {'form': form})

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = forms.FormUser(data=request.POST)
        profile_form = forms.FormUserProfileInfo(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            #NOTE: ModelForm.save() and Model.save() BOTH update the databases
            #Having both gives the flexibility below.
            #When the ModeForm is saved, we'll get the Model object.
            #You can then update the Model object further and then save again.
            #IF the object will be in a bad state without that extra
            #update, then we'll need to save the ModelForm with commit = False.
            #Then save the Model object after all the necessary updates
            #have been done.

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            #Set up the one-to-one relationship
            #Don't commit yet until it is done
            profile = profile_form.save(commit=False)
            profile.user = user

            #Note: profile_pic refers to the member of UserProfileInfo
            #, it's not referring to the media location
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True


        else:

            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.FormUser()
        profile_form = forms.FormUserProfileInfo()

    return render(request, 'sample_app/registration.html',
                            {'rego_form': user_form,
                            'profile_form': profile_form,
                            'registered': registered
                            })

#using login_required decorator to make sure the user is logged in first.
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active: #it's possible to deactive inactive users
                login(request, user)
                #'reverse look-up' the 'index', which is the name for the
                #corresponding URL and then redirect the user there
                #This is similar to {% url 'app_name:view_name'%}
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to log in and failed!")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, "sample_app/login.html", {})

sample_project/templates/sample_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top bg-success navbar-custom">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class='navbar-brand' href="{% url 'index'%}">HOME</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='navbar-link' href="{% url 'sample_app:register'%}">Register</a></li>
          <li><a class='navbar-link' href="{% url 'sample_app:help'%}">Help</a></li>

          {% if user.is_authenticated %} <!--Assuming that logging in puts the user in the global context?-->
          <li><a class='navbar-link' href="{% url 'logout'%}">Logout</a></li>
          {% else %}
          <li><a class='navbar-link' href="{% url 'sample_app:user_login'%}">Login</a></li>
          {%endif%}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend this template! -->
      {% endblock %}
    </div>
  </body>
</html>

sample_project/templates/sample_app/features_test.html
<!DOCTYPE html>
{% extends "sample_app/base.html" %}
{% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <h1>Testing Django Features</h1>
        <h2>List of Access records</h2>
        <div class="djangotwo">
          {% if access_records %}
          <table>
            <thead>
              <th>Site Name</th>
              <th>Date Accessed</th>

              {% for acc in access_records %}
              <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
              </tr>
              {% endfor %}

            </thead>
          </table>
          {% else %}
          <p>NO ACCESS RECORD FOUND</p>
          {% endif %}

          </div>
          <h2>Templated urls, forms, static image test, admin page, etc.</h2>
          <!--What out: there shouldn't be any unnecessary space in the template tag below! -->
          <p>To see the content of the WebUser table (fake users): <a href="{% url 'sample_app:users'%}">click here</a></p>
          <p>To see the 'help' page: <a href="{% url 'sample_app:help'%}">click here</a></p>
          <p>To use a form that doesn't do anything (and see how validation works): <a href="{% url 'sample_app:form_name'%}">click here</a></p>
          <p>To use a form to add new WebUser: <a href="{% url 'sample_app:form_enter_user'%}">click here</a></p>
          <!-- <p><a href="{% url 'sample_app:relative' %}">CLICK HERE TO TEST RELATIVE PATH IN TEMPLATE</a></p> -->
          <p>For the admin index page: <a href="{% url 'admin:index' %}">click here</a>. Note that the User in admin are
          the actual admin users of this website, wherease the WebUser is just a demo data table.</p>
      </div>
      <p><a href='{%url 'index'%}'>Return Home</a></p>
    </div>
{%endblock%}

sample_project/templates/sample_app/form_page.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
  </head>
  <body>
    <div class="container">
      <h1>Fill out the form</h1>
      <form method="post">
        {{form.as_p}}
        {% csrf_token %} <!-- Security feature - adding a hidden input - must have -->
      <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
    <p><a href='{%url 'index'%}'>Return Home</a></p>
  </body>
</html>

sample_project/templates/sample_app/help.html
<!DOCTYPE html>
{% load static %} <!--NOTE: load staticfiles is removed in Django 3 and later.-->
<html>
  <head>
    <!--  The head contains Meta-data -->
    <!-- Use html+Tab to get the boilerplate  -->
    <!-- Use cmd+/ to get the html comment line -->
    <meta charset="utf-8">
    <link rel="stylesheet" href='{% static "css/styles.css" %}'/>
    <title> Help Page </title>
  </head>
  <body>
    <!-- The body contains the actual content -->
    <h1>Looking for support?</h1>
    <p><strong>Help Info:</strong> {{ help_info }}</p>
    <p><a href='{%url 'index'%}'>Return Home</a></p>
  </body>
</html>

sample_project/templates/sample_app/index.html
<!DOCTYPE html>
{% extends "sample_app/base.html" %}
{% load static %}
{% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <h1>{% if user_name %}Hello {{user_name}}, w{%else%}W{% endif %}elcome to my Django sample project!</h1>
        <p>This is a basic full-stack Django website/web application.
        This website utilises HTML, CSS/Boostrap and JavaScript/JQuery in the front-end
      and Python/Django and SQLite in the back-end. The website is hosted on PyhonAnywhere
    and the source code is available on GitHub.</p>
    <p>This sample website follows the Django architecture below and will serve
    as an example of how to build a simple full-stack Django web application.</p>
    <p>
      <strong>Versions:</strong> Python - 3.9, Django - 3.2.5, Bootstrap - 3.3.7, JQuery - 3.5.1
    </p>
      <figure class="figure">
        <img class="figure-img img-fluid rounded" src='{% static "images/DjangoArchitecture.png" %}' alt="DjangoArchitecture.png"/>
        <figcaption class="figure-caption">Django Artchitecture (Source:Pierian Data/Udemy course - Django Bootcamp).</figcaption>
      </figure>
      </div>
    </div>
    <!-- Include the content of another HTML file -->
    {% include "sample_app/instructions.html"%}

    <div class="container">
      <div class="jumbotron">
        <h2>Explore</h2>
        <!--What out: there shouldn't be any unnecessary space in the template tag below! -->
        <p>Visit this page to check out some basic features of the website: <a href="{% url 'sample_app:features_test'%}">CLICK HERE</a></p>
        <p><strong>Note: you can register for an account to access many features of this website.</strong></p>
        <p><strong>Note: you will NOT be able to access the Admin feature of this website. However, you can follow the instructions above
        and set up this website on your own computer. You will THEN be able to access the Admin feature using the login details of the
      "superuser" you create as part of the process above.</strong></p>
      </div>
    </div>
{%endblock%}

sample_project/templates/sample_app/instructions.html
<!DOCTYPE html>
{%load static%}
<div class="container">
  <div class="jumbotron">
    <h2>Instructions for students (December 2021)</h2>
    <p>To download the website and set up development environment to develop
    and test it on your own local computer, follow the instructions below.</p>
    <button type="button" class="btn btn-info btn_arrow" data-toggle="collapse" data-target="#envs">1. Prepare environment</button>
    <button type="button" class="btn btn-info btn_arrow" data-toggle="collapse" data-target="#source">2. Get source</button>
    <button type="button" class="btn btn-info btn_arrow" data-toggle="collapse" data-target="#atom">3. Get editor</button>
    <button type="button" class="btn btn-info btn_arrow" data-toggle="collapse" data-target="#test_local">4. Test locally</button>

    <div id="envs" class="collapse">
      <h3>Prepare the environment</h3>
      <ul>
        <li>Install the latest version of <a href="https://docs.conda.io/en/latest/miniconda.html">miniconda</a>
          (to help ease the management of Python packages and virtual environments)</li>
          <li>Create a new virtual environment for Django development:<br>
            Open the miniconde console (anaconda prompt) and run
            <pre><code>conda create --name myDjangoEnv python=3.9<br>conda activate myDjangoEnv
  </code></pre>
  <strong>Note: pick the latest version for Python.</strong><br>
          Check to make sure the environment has been created:
          <pre><code>conda info --envs</code></pre>
          You should also see the console prompt changed to include "myDjangoEnv".
          From now on all Django development should take place within this virtual environment.
          If you want to switch to the "base" environment, simply deactivate the Django environment with:
          <pre><code>conda deactivate myDjangoEnv</code></pre>
          </li>
          <li>Install the necessary Python packages.
            Make sure you're still in the virtual enviroment created above. Everything you're installing now
            should only exist within that environment.
            <ul>
              <li>Django: <code>pip install django</code></li>
              <li>Pillow (for image management): <code>pip install pillow</code></li>
              <li>Security features:
                <code>pip install bcrypt</code>,
              <code>pip install django[argon2]</code></li>
              <li>Other utilities (environment files, raw SQL, fake data for testing etc.):
                <ul>
                  <li><code>pip install python-decouple</code></li>
                  <li><code>pip install django-sql</code></li>
                  <li><code>pip install faker</code></li>
                </ul>
              </li>
            </ul>
          </li>
      </ul>
    </div>

    <div id="source" class="collapse">
      <h3>Get the source code</h3>
      <ul>
        <li>Donwload and install <a href="https://git-scm.com/#">Git</a></li>
        <li>Sign up for a <a href="https://github.com/#">GitHub</a> account and then download and install <a href="https://desktop.github.com/#">GitHub Desktop</a></li>
        <li>Create a new folder in a safe place for the code</li>
        <li>Visit my <a href="https://github.com/MrN83/DjangoWorkSample.git">GitHub repository</a> and click the Fork button (below)
          <figure class="figure">
            <img class="figure-img img-fluid rounded" src='{% static "images/GitHub_ForkButton.png" %}' alt="GitHub_ForkButton.png"/>
            <figcaption class="figure-caption">Click the fork button.</figcaption>
          </figure>
          This will copy my code into your GitHub account to create your own "repository". <em>DO NOT CLONE my public repository, it's better for you to have
          your own copy. If my code changes in the future, you can always fork again.</em>
        </li>
        <li>In the new folder (created before), clone <em>your own repository</em> - using the Git Bash console (or GitHub desktop if you're not a fan of commandline interfaces)
          <pre><code>git clone [THE HTTP ADDRESS OF YOUR GITHUB REPOSITORY]</code></pre>
          Check your folder and see if you have all the files from my repository (<a href="https://github.com/MrN83/DjangoWorkSample.git">click here</a>)
        </li>
      </ul>
    </div>

    <div id="atom" class="collapse">
      <h3>Get a text editor (Atom)</h3>
      <p>All you need now is a text editor to open the code and start developing. I strongly recommend Atom for
      your text editor because it is fairly easy to use and can be extended to become (almost) a one-stop shop for
    everything you'd need.</p>
    <ul>
      <li>Download and install <a href="https://atom.io/">Atom</a></li>
      <li>Add to Atom the following packages:
        <ol>
          <li>atom-django (for Django support)</li>
          <li>autocomplete-python-jedi (autocomplete code for higher coding efficiency)</li>
          <li>platformio-ide-terminal (to run the commandline console from within Atom)<br>
            Make sure to configure the package to set Shell Override to C:\WINDOWS\System32\cmd.exe - for Windows users.
          </li>
        </ol>
      </li>
      <li>Close Atom and open (or close and re-open) the Miniconda console
        <ul>
          <li>Check that the Djangon virtual environment is running</li>
          <li>Run the following command to open Atom in this virtual environment
          <pre><code>atom --new-instance</code></pre>
          </li>
          <li>Add the <em>sample_project</em> folder (that you got from GitHub) to Atom and open the commandline console and
          start working!</li>
        </ul>
        <strong>From now on, you should start Atom this way (conda activate environment, atom --new-instance) to make sure
        Atom runs within the virtual environment.</strong>
      </li>
    </ul>
    </div>

    <div id="test_local" class="collapse">
      <h3>Test locally</h3>
      <p>To test the project, you will need to set up the database, populate some fake data, create a super user (admin)
      and then start the website from localhost. It's easier than it sounds and you'll be doing this regularly so you will
    not forget. Follow these steps below.</p>
    <ol>
      <li>Start Atom from the virtual environment, open the commandline console in Atom</li>
      <li>Find sample_project/settings.py, comment out two lines of code and uncomment another two
        so that SECRET_KEY is 'django-insecure....' and DEBUG is True, like this:
<pre><code>
  # TO BE USED IN LOCAL DEVELOPMENT ONLY:
  SECRET_KEY = 'django-insecure-=d&fhnb=ncw=%m!(##7)45d8&ph=nw#xn!dv!*t77wgplr#d%*'
  #SECRET_KEY = config("SECRET_KEY")

  # SECURITY WARNING: don't run with debug turned on in production!
  # TO BE USED IN LOCAL DEVELOPMENT ONLY:
  DEBUG = True
  #DEBUG = config('DEBUG', cast=bool)
</code> </pre>

      </li>
      <li>Navigate to the outside sample_project folder (which is the "root folder" of this project). Learn to use commands such as
      <code>dir</code> and <code>cd</code> to accomplish this. Use <code>dir</code> to make sure you can see the file
        <code>manage.py</code> in the current folder.</li>
      <li>The database must be set up with the data model in the code, run these commands in sequence:
        <pre><code>python manage.py migrate<br>python manage.py makemigrations sample_app<br>python manage.py migrate</code></pre>
      </li>
      <li>Fake data needs to be populated for testing, run this command:
        <pre><code>python populate_sample_app.py</code></pre>
      </li>
      <li>Create a super user to manage the Admin page, which would allow you to check the database, as well as running raw SQL.
        <pre><code>python manage.py createsuperuser</code></pre>
        Make sure to come up with a good username and password!
      </li>
      <li>Finally, run the server:
        <pre><code>python manage.py runserver</code></pre>
        Check and make sure that there are no errors (and make sure that the runserver
        command is still running the whole time, because that is basically the "server"). Then open a Chrome browser
        and copy and paste in the localhost url (http://127.0.0.1:8000/). You should
        see the home page of this website. Congratulations!
      </li>
      <li>Explore the website and see if everything works!</li>

    </ol>
    </div>

  </div>
</div>

sample_project/templates/sample_app/login.html
{% extends 'sample_app/base.html' %}
{% block body_block%}

<div class="jumbotron">
  <h1>Please login</h1>
  <form class="" action="{%url 'sample_app:user_login'%}" method="post">
    {%csrf_token%}
    <label for="username">Username:</label>
    <input type="text" name="username" value="Enter username">
    <label for="password">Password:</label>
    <input type="password" name="password" value="">
    <input type="submit" name="" value="Login">
  </form>

  <p>Or <a href="{%url 'sample_app:register'%}">register here</a></p>
</div>






{%endblock%}

sample_project/templates/sample_app/registration.html
{% extends "sample_app/base.html" %}
{% load static %}

{%block body_block%}

<div class="jumbotron">
  {%if registered%}
    <h1>Thank you for registering!</h1>
  {%else %}
    <h1>Register here!</h1>
    <h3>Fillout the form:</h3>

    <!-- enc type is needed for image uloading -->
    <form enctype="multipart/form-data" method="post">
      {%csrf_token%}
      {{rego_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>

  {%endif%}
</div>

{%endblock%}

sample_project/templates/sample_app/relative_url_templates.html
<!DOCTYPE html> <!-- Must always be here -->
{% extends "sample_app/base.html"%}
<!-- {perc extends url "sample_app:base_template" perc} THIS DOESN'T WORK :)
"perc" is %, needed to make sure Django doesn't try to execute the code :P
-->
{% block body_block %}
<h1>Welcome to the relative url templates!!!</h1>
<p>This is an example of template inheritance!</p>
<p><a href='{%url 'index'%}'>Return Home</a></p>
{% endblock %}